dist: trusty
sudo: required
services:
  - docker

env:
  global:
  - DOCKER_VERSION=1.13.1-0~ubuntu-trusty
  matrix:
  - TEST_TARGET: docker-oauth2_proxy

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-engine=${DOCKER_VERSION}
  - docker version
  - docker info

script:
  - make $TEST_TARGET

notifications:
  slack:
    secure: mWvCuaNCHNhKpTxNBOUI8+OPYMYwycuD2hNHCAsSKGy2krvAAWLc2P6fsedGVferjMen7ycJQOjaTr6WxlOgF413iCG4IcR15gcQIrtBO2HggIeK9V7bpGOMeLTcQh+ewSSGF1g4X/9fWqMM8cRYPUfzf27XuiKIkZmLRCXaosmTOCCEZ9+/C0q0ywsDwdb06kJR2R3kTWHPhoiT2qxWStIFsm+SVktT+Z8ocPxy4rY6mKTYWFII8rWpx+OmY1TeMpdR4+OS2WSpPCxEqz6MFr6pIxfi3JiCIvtjTUaIDPOZKDaqlEZn6TWYwcHVLcPtVBPKd6/tJaYV0FwOEbWumPLbcP2IwcfrpjaVxJ0J6e49R8r/eMt2vhNUrRhIw/UqKfReRxUNPp6KLKhxyryV7AxEqesstUaCKK2E+H86GZwbqRnvCwKB/TPcwfwbs+DOepuNthc617/scyEk7hTkbdiOOEyu146KCWQO3eweCxbZEMGnKCj/lwlyizTpFYP3g9eLPE6swExvGs3JFrKiiDy+KwCZ3ZF+mLbVSdMN1I3iryxBAUYcYuBmv/b2QLwYhCUkvaUgw2UALS2XjuK1twsVzkFQLDDtxn8kALbwbCWlYYtD17FDwx58WnAZoWgFb0I9yGVEcpKhwFg/nPl/15FOmuL4861rph33vgaiang=